// src/services/reporting/exportRACI.js

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType
} from 'docx';

/**
 * EXPORT RACI REPORT (CRA ENGINE – VITE SAFE)
 */
export const exportRACIPDF = async ({
  risks = [],
  userData = {},
  assessmentConfig
}) => {
  const tableRows = [
    new TableRow({
      children: [
        new TableCell({ children: [new Paragraph('Risk')] }),
        new TableCell({ children: [new Paragraph('Responsible')] }),
        new TableCell({ children: [new Paragraph('Accountable')] }),
        new TableCell({ children: [new Paragraph('Consulted')] }),
        new TableCell({ children: [new Paragraph('Informed')] })
      ]
    }),
    ...risks.map(risk =>
      new TableRow({
        children: [
          new TableCell({ children: [new Paragraph(risk.title || '-')] }),
          new TableCell({ children: [new Paragraph(risk.responsible || '-')] }),
          new TableCell({ children: [new Paragraph(risk.accountable || '-')] }),
          new TableCell({ children: [new Paragraph(risk.consulted || '-')] }),
          new TableCell({ children: [new Paragraph(risk.informed || '-')] })
        ]
      })
    )
  ];

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            children: [
              new TextRun({
                text: 'RACI MATRIX REPORT',
                bold: true,
                size: 32
              })
            ]
          }),
          new Paragraph(`Generated by: ${userData?.name || 'System'}`),
          new Table({
            width: {
              size: 100,
              type: WidthType.PERCENTAGE
            },
            rows: tableRows
          })
        ]
      }
    ]
  });

  const blob = await Packer.toBlob(doc);

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'RACI_Report.docx';
  a.click();

  URL.revokeObjectURL(url);
};
